apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: simple-serving
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    containers:
      - name: kserve-container
        image: docker.io/s0026942030/simple-test:latest
        imagePullSecrets:
          - name: rajdoc-registry
