apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: simple-serving
spec:
  template:
    metadata: {}            # optional but safe
    spec:
      predictor:
        type: lowConcurrency
        minReplicas: 1
        maxReplicas: 1
        imagePullSecrets:
        - name: rajdoc-registry
        containers:
        - name: kserve-container
          image: docker.io/s0026942030/simple-test:latest
