apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: simple-serving
spec:
  template: 
    apiVersion: "serving.kserve.io/v1beta1"
    kind: InferenceService
    metadata:
      name: simple-serving
    spec:
      predictor:
        imagePullSecrets:
          - name: rajdoc-registry
        containers:
          - name: kserve-container
            image: docker.io/s0026942030/simple-test:latest
